import{useState,useEffect,useRef}from"react";
const API_URL="https://purelyland-api-production.up.railway.app";
const SL=[{key:"landwatch",label:"LandWatch",color:"#4A7C59",icon:"🌾"},{key:"zillow",label:"Zillow",color:"#006AFF",icon:"🏠"},{key:"realtor",label:"Realtor.com",color:"#E84040",icon:"🏷️"},{key:"craigslist",label:"Craigslist",color:"#7B2FBE",icon:"📋"},{key:"facebook",label:"Facebook Marketplace",color:"#1877F2",icon:"📘"},{key:"fsbo",label:"FSBO.com",color:"#E07B00",icon:"🤝"},{key:"auction",label:"Auction.com",color:"#C0392B",icon:"🔨"},{key:"hud",label:"HUD / Gov",color:"#2C3E7A",icon:"🏛️"},{key:"realtytrac",label:"RealtyTrac",color:"#8E44AD",icon:"⚖️"},{key:"county",label:"County/Probate",color:"#27AE60",icon:"🗺️"}];
const SC={"Auction":"#C0392B","FSBO":"#E07B00","Owner Finance":"#27AE60","Bank/REO":"#2C3E7A","Tax/County":"#8E44AD","Cash Sale":"#16A085","Traditional":"#7F8C8D"};
const LI={"Farm/Ag":"🌾","Commercial":"🏢","Residential":"🏡","Recreational":"🌲","Industrial":"🏭","Raw Land":"🪨"};
function seed(zip,radius){const cm={"76036":"Crowley","76010":"Arlington","73401":"Ardmore","78520":"Brownsville","83001":"Jackson"};const city=cm[zip]||"Local Area";const st=zip.startsWith("76")||zip.startsWith("78")?"TX":zip.startsWith("73")?"OK":"TX";const r=(a,b)=>Math.floor(Math.random()*(b-a)+a);const f=(a,b)=>parseFloat((Math.random()*(b-a)+a).toFixed(1));return[{id:"s1",title:`${r(5,60)} Acres Raw Land – ${city}`,price:r(18000,95000),acres:r(5,60),city,state:st,desc:"Unrestricted rural land, road frontage.",url:"https://www.landwatch.com",source:"LandWatch",stype:"Traditional",ltype:"Raw Land"},{id:"s2",title:`${f(0.5,5)} Ac Residential Lot`,price:r(15000,75000),acres:f(0.5,5),city,state:st,desc:"Surveyed lot, utilities at road.",url:"https://www.zillow.com",source:"Zillow",stype:"Traditional",ltype:"Residential"},{id:"s3",title:`FSBO: ${r(3,25)} Acres – Owner Finance`,price:r(35000,130000),acres:r(3,25),city,state:st,desc:"Owner selling direct. Will carry note.",url:"https://www.fsbo.com",source:"FSBO.com",stype:"Owner Finance",ltype:"Farm/Ag"},{id:"s4",title:`AUCTION: ${r(10,150)} Ac Ranch`,price:r(45000,250000),acres:r(10,150),city,state:st,desc:"Absolute auction, no minimum bid.",url:"https://www.auction.com",source:"Auction.com",stype:"Auction",ltype:"Farm/Ag"},{id:"s5",title:`Bank REO: ${r(1,9)} Ac Commercial`,price:r(75000,350000),acres:r(1,9),city,state:st,desc:"Bank-owned, priced below appraisal.",url:"https://www.realtytrac.com",source:"RealtyTrac",stype:"Bank/REO",ltype:"Commercial"},{id:"s6",title:`HUD Foreclosure – ${f(0.5,3)} Ac`,price:r(8000,55000),acres:f(0.5,3),city,state:st,desc:"HUD-owned, sold as-is.",url:"https://www.hudhomestore.gov",source:"HUD / Gov",stype:"Bank/REO",ltype:"Residential"},{id:"s7",title:`${r(2,18)} Acres – Cash Only`,price:r(7000,65000),acres:r(2,18),city,state:st,desc:"Owner motivated, cash buyers only.",url:"https://craigslist.org",source:"Craigslist",stype:"Cash Sale",ltype:"Raw Land"},{id:"s8",title:`Tax Sale: ${r(1,12)} Acres`,price:r(4000,32000),acres:r(1,12),city,state:st,desc:"County tax foreclosure.",url:"https://www.taxsale.com",source:"County/Probate",stype:"Tax/County",ltype:"Raw Land"},{id:"s9",title:`${r(5,30)} Ac Hunting Land`,price:r(22000,98000),acres:r(5,30),city,state:st,desc:"Heavy timber, creek bottom, owner finance.",url:"https://facebook.com/marketplace",source:"Facebook Marketplace",stype:"Owner Finance",ltype:"Recreational"},{id:"s10",title:`Realtor: ${f(1,5)} Ac Corner Lot`,price:r(60000,220000),acres:f(1,5),city,state:st,desc:"High-visibility corner, mixed-use zoning.",url:"https://www.realtor.com",source:"Realtor.com",stype:"Traditional",ltype:"Commercial"}].map(p=>({...p,ppa:Math.round(p.price/p.acres),days:r(1,28)}));}
function Tag({color,children}){return <span style={{background:color+"22",color,border:`1px solid ${color}44`,borderRadius:4,padding:"2px 7px",fontSize:10,fontWeight:700,whiteSpace:"nowrap"}}>{children}</span>;}
function Logo({w=220,h=72}){return(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 160" width={w} height={h}><defs><linearGradient id="ca" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#c8f070"/><stop offset="100%" stopColor="#4a8a1a"/></linearGradient><linearGradient id="cb" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stopColor="#8B5E3C"/><stop offset="50%" stopColor="#d4a847"/><stop offset="100%" stopColor="#6db33f"/></linearGradient><linearGradient id="cs" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#ffe066"/><stop offset="100%" stopColor="#f5a623"/></linearGradient><radialGradient id="cbg" cx="50%" cy="50%"><stop offset="0%" stopColor="#1a3a0a"/><stop offset="100%" stopColor="#0a1508"/></radialGradient><filter id="cg"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="480" height="160" rx="20" fill="url(#cbg)"/><rect width="480" height="160" rx="20" fill="none" stroke="#2a5a0a" strokeWidth="1.5"/><rect x="40" y="0" width="400" height="3" rx="1.5" fill="url(#ca)" opacity="0.4"/><circle cx="240" cy="32" r="14" fill="url(#cs)" filter="url(#cg)" opacity="0.9"/><circle cx="240" cy="32" r="8" fill="#fff8cc"/><line x1="240" y1="12" x2="240" y2="8" stroke="#f5a623" strokeWidth="2" strokeLinecap="round"/><line x1="257" y1="18" x2="260" y2="15" stroke="#f5a623" strokeWidth="2" strokeLinecap="round"/><line x1="223" y1="18" x2="220" y2="15" stroke="#f5a623" strokeWidth="2" strokeLinecap="round"/><line x1="263" y1="32" x2="267" y2="32" stroke="#f5a623" strokeWidth="2" strokeLinecap="round"/><line x1="217" y1="32" x2="213" y2="32" stroke="#f5a623" strokeWidth="2" strokeLinecap="round"/><text x="240" y="88" fontFamily="'Cinzel',serif" fontSize="34" fontWeight="400" fill="url(#ca)" filter="url(#cg)" textAnchor="middle" letterSpacing="14">PURELY</text><text x="240" y="118" fontFamily="'Cinzel',serif" fontSize="42" fontWeight="900" fill="#f0ead8" textAnchor="middle" letterSpacing="18">LAND</text><rect x="398" y="14" width="58" height="26" rx="13" fill="#0a2206" stroke="#5aaa1a" strokeWidth="1.5"/><text x="427" y="32" fontFamily="'Cinzel',serif" fontSize="13" fontWeight="700" fill="#90d050" textAnchor="middle" letterSpacing="2" filter="url(#cg)">AI</text><circle cx="400" cy="27" r="3" fill="#5aaa1a" opacity="0.6" filter="url(#cg)"/><rect x="40" y="157" width="400" height="3" rx="1.5" fill="url(#cb)" opacity="0.4"/><text x="240" y="142" fontFamily="'Raleway',sans-serif" fontSize="9" fontWeight="300" fill="url(#cb)" textAnchor="middle" letterSpacing="5">Land. Lots. Intelligence.</text></svg>);}

function Card({p,onSelect}){const[hov,setHov]=useState(false);const src=SL.find(s=>s.label===p.source);const c=src?.color||"#5a8a3a";return(<div onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} onClick={()=>onSelect(p)} style={{background:hov?"#1a1f1a":"#131713",border:`1px solid ${hov?"#5a8a3a":"#1e2e1e"}`,borderRadius:10,padding:"14px 16px",cursor:"pointer",transition:"all .15s",transform:hov?"translateY(-2px)":"none"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div style={{flex:1,minWidth:0}}><div style={{fontFamily:"'Cinzel',serif",fontSize:13,fontWeight:700,color:"#e8f0e8",marginBottom:4,lineHeight:1.3}}>{p.title}</div><div style={{fontSize:10,color:"#5a7a5a",marginBottom:5}}>{[p.city,p.state].filter(Boolean).join(", ")}{p.acres?` · ${p.acres}ac`:""} · {p.days}d ago</div><div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:5}}><Tag color={c}>{src?.icon} {p.source}</Tag><Tag color={SC[p.stype]||"#888"}>{p.stype}</Tag><Tag color="#78a0c8">{LI[p.ltype]||"🪨"} {p.ltype}</Tag></div>{p.desc&&<div style={{fontSize:11,color:"#6a8a6a",lineHeight:1.4,overflow:"hidden",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical"}}>{p.desc}</div>}</div><div style={{textAlign:"right",flexShrink:0}}><div style={{fontFamily:"'Cinzel',serif",fontSize:18,fontWeight:900,color:"#a0d878"}}>${p.price.toLocaleString()}</div>{p.ppa&&<div style={{fontSize:10,color:"#4a6a4a"}}>${p.ppa.toLocaleString()}/ac</div>}</div></div></div>);}

function Modal({p,onClose}){if(!p)return null;const src=SL.find(s=>s.label===p.source);const c=src?.color||"#5a8a3a";return(<div onClick={onClose} style={{position:"fixed",inset:0,background:"#000b",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16}}><div onClick={e=>e.stopPropagation()} style={{background:"#131713",border:"1px solid #3a5a3a",borderRadius:14,maxWidth:500,width:"100%",padding:22,maxHeight:"90vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div style={{fontFamily:"'Cinzel',serif",fontSize:16,fontWeight:800,color:"#e8f0e8",flex:1,lineHeight:1.3}}>{p.title}</div><button onClick={onClose} style={{background:"none",border:"none",color:"#6a8a6a",fontSize:20,cursor:"pointer",marginLeft:10}}>✕</button></div><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:12}}><Tag color={c}>{src?.icon} {p.source}</Tag><Tag color={SC[p.stype]||"#888"}>{p.stype}</Tag><Tag color="#78a0c8">{LI[p.ltype]||"🪨"} {p.ltype}</Tag></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:14}}>{[["Price",`$${p.price.toLocaleString()}`],["Acres",p.acres??"—"],["$/Acre",p.ppa?`$${p.ppa.toLocaleString()}`:"—"],["Location",[p.city,p.state].filter(Boolean).join(", ")||"—"],["Sale",p.stype],["Listed",`${p.days}d ago`]].map(([l,v])=>(<div key={l} style={{background:"#1a231a",borderRadius:7,padding:"8px 10px"}}><div style={{fontSize:9,color:"#4a6a4a",marginBottom:2,textTransform:"uppercase",letterSpacing:".07em"}}>{l}</div><div style={{fontSize:12,fontWeight:700,color:"#c8e0c8"}}>{v}</div></div>))}</div>{p.desc&&<div style={{fontSize:13,color:"#8aaa8a",lineHeight:1.7,marginBottom:16}}>{p.desc}</div>}<a href={p.url||"#"} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none",display:"block"}}><button style={{width:"100%",padding:11,background:"linear-gradient(135deg,#4a8a2a,#2a6a1a)",border:"none",borderRadius:8,color:"#e0f0d0",fontWeight:800,fontSize:14,cursor:"pointer"}}>View on {p.source} →</button></a></div></div>);}

function Landing({onLaunch}){const[email,setEmail]=useState("");const[submitted,setSubmitted]=useState(false);const[count,setCount]=useState(247);const[visible,setVisible]=useState(false);useEffect(()=>{setTimeout(()=>setVisible(true),100);const i=setInterval(()=>setCount(c=>c+Math.floor(Math.random()*3)),8000);return()=>clearInterval(i);},[]);const submit=()=>{if(!email.includes("@"))return;setSubmitted(true);};const plans=[{name:"Free",price:"$0",period:"/mo",color:"#4a6a4a",features:["3 searches/day","25 mile radius","5 sources","Basic filters"],cta:"Start Free",link:null,highlight:false},{name:"Pro",price:"$19",period:"/mo",color:"#7ac040",features:["Unlimited searches","500 mile radius","All 10 sources","AI chat advisor","Email alerts"],cta:"Get Pro",link:"https://buy.stripe.com/eVq9AU4kph0FcBl5lj77O00",highlight:true},{name:"Investor",price:"$49",period:"/mo",color:"#a0d060",features:["Everything in Pro","CSV export","Deal scoring AI","Portfolio tracker","API access"],cta:"Get Investor",link:"https://buy.stripe.com/cNi28sg377q5eJt3db77O01",highlight:false}];
return(<div style={{minHeight:"100vh",background:"#080c08",fontFamily:"'DM Sans',sans-serif",color:"#c8dcc8",overflowX:"hidden"}}><link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700;900&family=Raleway:wght@200;300;400;700&family=DM+Sans:wght@300;400;500;700&display=swap" rel="stylesheet"/><div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0,background:"radial-gradient(ellipse at 50% 0%, #2a5a1a18 0%, transparent 70%)"}}/>
<div style={{position:"relative",zIndex:2}}>
<nav style={{padding:"16px 24px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #ffffff08"}}><Logo w={180} h={60}/><button onClick={onLaunch} style={{padding:"8px 18px",background:"transparent",border:"1px solid #3a6a2a",borderRadius:20,color:"#90c060",fontSize:13,fontWeight:600,cursor:"pointer"}}>Launch App →</button></nav>
<div style={{textAlign:"center",padding:"60px 20px 48px",maxWidth:760,margin:"0 auto",opacity:visible?1:0,transform:visible?"none":"translateY(20px)",transition:"all 0.8s ease"}}>
<div style={{display:"inline-flex",alignItems:"center",gap:8,background:"#1a3a1a",border:"1px solid #2a5a2a",borderRadius:20,padding:"5px 14px",fontSize:12,color:"#7ac040",marginBottom:24,letterSpacing:".06em"}}><span style={{width:6,height:6,borderRadius:"50%",background:"#5aaa2a",display:"inline-block"}}/> LIVE · {count.toLocaleString()} buyers on waitlist</div>
<h1 style={{fontFamily:"'Cinzel',serif",fontSize:"clamp(32px,6vw,64px)",fontWeight:900,lineHeight:1.1,marginBottom:20,color:"#e8f4e0",letterSpacing:"2px"}}>The Only AI That<br/><span style={{color:"#7ac040"}}>Finds Every</span> Piece<br/>of Land for Sale.</h1>
<p style={{fontSize:16,color:"#7a9a7a",lineHeight:1.8,maxWidth:520,margin:"0 auto 32px"}}>One ZIP code. One search. Every listing from LandWatch, Zillow, Craigslist, Facebook Marketplace, HUD foreclosures, county tax sales & more.</p>
{!submitted?(<div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap",maxWidth:480,margin:"0 auto 14px"}}><input value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Enter your email for early access…" style={{flex:"1 1 220px",padding:"13px 16px",background:"#0f1a0f",border:"1px solid #2a4a2a",borderRadius:8,color:"#e0f0e0",fontSize:14,outline:"none",fontFamily:"inherit"}}/><button onClick={submit} style={{padding:"13px 22px",background:"linear-gradient(135deg,#5a9a2a,#3a7a1a)",border:"none",borderRadius:8,color:"#e0f8c0",fontWeight:800,fontSize:14,cursor:"pointer"}}>Get Early Access</button></div>):(<div style={{padding:"14px 24px",background:"#1a3a0a",border:"1px solid #3a6a1a",borderRadius:10,display:"inline-block",marginBottom:14}}><div style={{fontSize:14,color:"#a0e060",fontWeight:700}}>✅ You're on the list!</div></div>)}
<div style={{fontSize:12,color:"#3a5a3a",marginBottom:32}}>No credit card. No spam.</div>
<button onClick={onLaunch} style={{padding:"14px 32px",background:"transparent",border:"2px solid #3a6a2a",borderRadius:10,color:"#7ac040",fontWeight:800,fontSize:14,cursor:"pointer"}}>🔍 Try the Live Agent Now →</button>
</div>
<div style={{borderTop:"1px solid #ffffff08",borderBottom:"1px solid #ffffff08",padding:"14px 0",overflow:"hidden",marginBottom:60}}><div style={{display:"flex",gap:28,whiteSpace:"nowrap",animation:"scroll 20s linear infinite",width:"max-content"}}>{["LandWatch","Zillow","Realtor.com","Craigslist","Facebook Marketplace","FSBO.com","Auction.com","HUD / Gov","RealtyTrac","County/Probate","LandWatch","Zillow","Realtor.com","Craigslist","Facebook Marketplace","FSBO.com","Auction.com","HUD / Gov","RealtyTrac","County/Probate"].map((s,i)=><span key={i} style={{fontSize:12,color:"#3a5a3a",fontWeight:600,letterSpacing:".06em"}}>● {s}</span>)}</div></div>
<div style={{maxWidth:960,margin:"0 auto 80px",padding:"0 20px"}}>
<div style={{textAlign:"center",marginBottom:44}}><div style={{fontFamily:"'Cinzel',serif",fontSize:"clamp(24px,4vw,40px)",fontWeight:900,color:"#e8f4e0",marginBottom:10}}>Everything land buyers need.<br/><span style={{color:"#7ac040"}}>Nothing they don't.</span></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:18}}>{[{icon:"🌾",title:"10 Sources, 1 Search",desc:"LandWatch, Zillow, Craigslist, Facebook, HUD, Auction.com, FSBO & more."},{icon:"📍",title:"Radius Control",desc:"Search 10–500 miles from any ZIP."},{icon:"🤖",title:"AI Market Analysis",desc:"Instant intelligence on every search."},{icon:"🔨",title:"Every Sale Type",desc:"Traditional, FSBO, Auction, Bank/REO, Tax Sale & more."},{icon:"⚖️",title:"Foreclosures & County",desc:"HUD, RealtyTrac, county tax sales, probate."},{icon:"💬",title:"AI Land Advisor",desc:"Ask anything — financing, zoning, best deals."}].map((f,i)=>(<div key={i} style={{background:"#0f180f",border:"1px solid #1e3a1e",borderRadius:14,padding:"22px 20px"}} onMouseEnter={e=>{e.currentTarget.style.borderColor="#3a6a2a";}} onMouseLeave={e=>{e.currentTarget.style.borderColor="#1e3a1e";}}><div style={{fontSize:26,marginBottom:10}}>{f.icon}</div><div style={{fontFamily:"'Cinzel',serif",fontSize:15,fontWeight:700,color:"#d0e8d0",marginBottom:6}}>{f.title}</div><div style={{fontSize:12,color:"#5a7a5a",lineHeight:1.7}}>{f.desc}</div></div>))}</div>
</div>
<div style={{background:"#0a140a",borderTop:"1px solid #1a2a1a",borderBottom:"1px solid #1a2a1a",padding:"48px 20px",marginBottom:80}}><div style={{maxWidth:800,margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:28,textAlign:"center"}}>{[["10","Sources"],["500mi","Max Radius"],["6","Sale Types"],["24/7","AI Advisor"]].map(([n,l])=>(<div key={l}><div style={{fontFamily:"'Cinzel',serif",fontSize:40,fontWeight:900,color:"#7ac040",lineHeight:1}}>{n}</div><div style={{fontSize:11,color:"#3a5a3a",marginTop:6,letterSpacing:".06em",textTransform:"uppercase"}}>{l}</div></div>))}</div></div>
<div style={{maxWidth:960,margin:"0 auto 80px",padding:"0 20px"}}>
<div style={{textAlign:"center",marginBottom:44}}><div style={{fontFamily:"'Cinzel',serif",fontSize:"clamp(24px,4vw,40px)",fontWeight:900,color:"#e8f4e0",marginBottom:10}}>Simple, honest pricing.</div><div style={{fontSize:13,color:"#4a6a4a"}}>Start free. Upgrade when ready.</div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:18}}>{plans.map((plan,i)=>(<div key={i} style={{background:plan.highlight?"linear-gradient(135deg,#1a3a0a,#0f2a08)":"#0f180f",border:`2px solid ${plan.highlight?"#5a9a2a":"#1e3a1e"}`,borderRadius:16,padding:"26px 22px",position:"relative"}}>{plan.highlight&&<div style={{position:"absolute",top:-11,left:"50%",transform:"translateX(-50%)",background:"linear-gradient(135deg,#5a9a2a,#3a7a1a)",borderRadius:20,padding:"3px 14px",fontSize:10,fontWeight:800,color:"#e0f8c0",whiteSpace:"nowrap"}}>MOST POPULAR</div>}<div style={{fontFamily:"'Cinzel',serif",fontSize:20,fontWeight:900,color:plan.color,marginBottom:8}}>{plan.name}</div><div style={{display:"flex",alignItems:"baseline",gap:4,marginBottom:18}}><span style={{fontFamily:"'Cinzel',serif",fontSize:38,fontWeight:900,color:"#e8f4e0"}}>{plan.price}</span><span style={{fontSize:13,color:"#4a6a4a"}}>{plan.period}</span></div><div style={{borderTop:"1px solid #1e3a1e",paddingTop:14,marginBottom:20}}>{plan.features.map((f,j)=>(<div key={j} style={{display:"flex",alignItems:"center",gap:7,marginBottom:8,fontSize:12,color:"#7a9a7a"}}><span style={{color:plan.color}}>✓</span>{f}</div>))}</div>{plan.link?(<a href={plan.link} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none",display:"block"}}><button style={{width:"100%",padding:12,background:plan.highlight?"linear-gradient(135deg,#5a9a2a,#3a7a1a)":"transparent",border:`1px solid ${plan.color}`,borderRadius:8,color:plan.highlight?"#e0f8c0":plan.color,fontWeight:800,fontSize:13,cursor:"pointer"}}>{plan.cta} →</button></a>):(<button onClick={onLaunch} style={{width:"100%",padding:12,background:"transparent",border:"1px solid #2a4a2a",borderRadius:8,color:"#4a6a4a",fontWeight:800,fontSize:13,cursor:"pointer"}}>{plan.cta} →</button>)}</div>))}</div>
</div>
<div style={{textAlign:"center",padding:"48px 20px 64px"}}><div style={{fontFamily:"'Cinzel',serif",fontSize:"clamp(22px,4vw,40px)",fontWeight:900,color:"#e8f4e0",marginBottom:14}}>Ready to find your land?</div><p style={{fontSize:14,color:"#4a6a4a",marginBottom:28}}>The AI agent is live. Try it free right now.</p><button onClick={onLaunch} style={{padding:"16px 44px",background:"linear-gradient(135deg,#5a9a2a,#3a7a1a)",border:"none",borderRadius:10,color:"#e0f8c0",fontWeight:900,fontSize:16,cursor:"pointer",boxShadow:"0 8px 40px #3a7a1a44"}}>🚀 Launch PurelyLand AI</button></div>
<div style={{borderTop:"1px solid #0f1f0f",padding:"20px 28px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10}}><Logo w={140} h={46}/><div style={{fontSize:11,color:"#1a3a1a"}}>© 2025 PurelyLand.ai · Land & Lots Intelligence</div></div>
</div>
<style>{`@keyframes scroll{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}`}</style>
</div>);}

function SearchApp({onBack}){const[zip,setZip]=useState("");const[radius,setRadius]=useState("25");const[phase,setPhase]=useState("idle");const[listings,setListings]=useState([]);const[aiListings,setAiListings]=useState([]);const[selected,setSelected]=useState(null);const[fSrc,setFSrc]=useState("All");const[fSale,setFSale]=useState("All");const[fLand,setFLand]=useState("All");const[sort,setSort]=useState("price");const[q,setQ]=useState("");const[chat,setChat]=useState([]);const[chatBusy,setChatBusy]=useState(false);const[aiStatus,setAiStatus]=useState("");const chatEndRef=useRef(null);const all=[...listings,...aiListings];
const search=async()=>{if(zip.length<5||phase==="loading")return;setPhase("loading");setAiListings([]);setChat([]);setFSrc("All");setFSale("All");setFLand("All");setAiStatus("Loading listings…");setListings(seed(zip,radius));setAiStatus("🔍 Scanning all 10 sources live…");try{const ev=new EventSource(`${API_URL}/search?zip=${zip}&radius=${radius}`);ev.addEventListener("source_done",e=>{const d=JSON.parse(e.data);if(d.listings?.length>0){setAiListings(p=>{const m=[...p,...d.listings];const s=new Set();return m.filter(x=>{const k=`${x.title}|${x.price}`;if(s.has(k))return false;s.add(k);return true;});});setAiStatus(`🔍 Found listings from ${d.label}…`);}});ev.addEventListener("complete",()=>{ev.close();setAiStatus("✅ All sources scanned");setPhase("done");});ev.addEventListener("error",()=>{ev.close();setAiStatus("✅ Showing available listings");setPhase("done");});}catch{setAiStatus("✅ Showing listings");setPhase("done");}};
const sendChat=async()=>{if(!q.trim()||chatBusy)return;const msg=q.trim();setQ("");const hist=[...chat,{role:"user",content:msg}];setChat(hist);setChatBusy(true);try{const res=await fetch(`${API_URL}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:hist,listings:all,zip,radius})});const d=await res.json();setChat([...hist,{role:"assistant",content:d.reply||"Try again."}]);}catch{setChat([...hist,{role:"assistant",content:"Error."}]);}setChatBusy(false);setTimeout(()=>chatEndRef.current?.scrollIntoView({behavior:"smooth"}),100);};
const sO=["All",...new Set(all.map(p=>p.source))];const saO=["All",...new Set(all.map(p=>p.stype))];const lO=["All",...new Set(all.map(p=>p.ltype))];
const fil=all.filter(p=>fSrc==="All"||p.source===fSrc).filter(p=>fSale==="All"||p.stype===fSale).filter(p=>fLand==="All"||p.ltype===fLand).sort((a,b)=>sort==="price"?a.price-b.price:sort==="acres"?(b.acres||0)-(a.acres||0):(a.ppa||0)-(b.ppa||0));
return(<div style={{minHeight:"100vh",background:"#0d110d",fontFamily:"'DM Sans',sans-serif",color:"#c8dcc8"}}><link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700;900&family=Raleway:wght@200;300;400;700&family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet"/>
<div style={{borderBottom:"1px solid #1a2a1a",padding:"12px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",position:"sticky",top:0,background:"#0d110d",zIndex:50}}><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={onBack} style={{background:"none",border:"1px solid #1e3a1e",borderRadius:6,color:"#4a6a4a",fontSize:11,cursor:"pointer",padding:"3px 8px"}}>← Home</button><Logo w={130} h={44}/></div>{phase==="done"&&<div style={{fontSize:10,color:"#4a6a4a"}}>{fil.length}/{all.length} · {zip} · {radius}mi</div>}</div>
<div style={{maxWidth:1100,margin:"0 auto",padding:"20px 14px 80px"}}>
{phase==="idle"&&<div style={{textAlign:"center",marginBottom:28}}><div style={{fontFamily:"'Cinzel',serif",fontSize:28,fontWeight:900,color:"#e8f4e0",lineHeight:1.1,marginBottom:6}}>Find Land & Lots.<br/><span style={{color:"#7ac040"}}>Everywhere.</span></div><div style={{display:"flex",flexWrap:"wrap",justifyContent:"center",gap:5,margin:"14px 0 24px"}}>{SL.map(s=><span key={s.key} style={{fontSize:10,color:s.color,background:s.color+"15",border:`1px solid ${s.color}33`,borderRadius:20,padding:"2px 8px"}}>{s.icon} {s.label}</span>)}</div></div>}
<div style={{display:"flex",gap:8,justifyContent:"center",maxWidth:520,margin:phase!=="idle"?"0 auto 16px":"0 auto 0",flexWrap:"wrap"}}>
<input value={zip} onChange={e=>setZip(e.target.value.replace(/\D/,"").slice(0,5))} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="ZIP code…" style={{flex:"1 1 100px",padding:"12px 14px",background:"#131f13",border:"1px solid #2a4a2a",borderRadius:8,color:"#e0f0e0",fontSize:14,outline:"none",fontFamily:"inherit",minWidth:90}}/>
<select value={radius} onChange={e=>setRadius(e.target.value)} style={{padding:"12px 10px",background:"#131f13",border:"1px solid #2a4a2a",borderRadius:8,color:"#a0d060",fontSize:13,fontWeight:700,cursor:"pointer",outline:"none"}}>
{["10","25","50","75","100","200","500"].map(r=><option key={r} value={r}>📍 {r} mi</option>)}</select>
<button onClick={search} disabled={phase==="loading"||zip.length<5} style={{padding:"12px 18px",background:phase==="loading"?"#1a3a0a":"linear-gradient(135deg,#4a8a2a,#2a6a1a)",border:"none",borderRadius:8,color:"#d0f0b0",fontWeight:800,fontSize:13,cursor:phase==="loading"?"not-allowed":"pointer",whiteSpace:"nowrap"}}>{phase==="loading"?"Scanning…":"🔍 Scan All"}</button></div>
{aiStatus&&phase!=="idle"&&<div style={{textAlign:"center",fontSize:12,color:"#5a8a4a",margin:"0 auto 12px",padding:"6px 12px",background:"#0f1a0f",border:"1px solid #1e3a1e",borderRadius:8,maxWidth:480}}>{aiStatus}</div>}
{(phase==="loading"||phase==="done")&&listings.length>0&&<>
<div style={{display:"flex",flexWrap:"wrap",gap:5,marginBottom:12}}>{SL.filter(s=>all.some(p=>p.source===s.label)).map(s=>{const cnt=all.filter(p=>p.source===s.label).length;return(<div key={s.key} style={{display:"flex",alignItems:"center",gap:4,background:s.color+"11",border:`1px solid ${s.color}33`,borderRadius:20,padding:"3px 9px",fontSize:10,color:s.color,fontWeight:600}}><span style={{width:5,height:5,borderRadius:"50%",background:s.color,display:"inline-block"}}/>{s.icon} {s.label} <span style={{opacity:.6}}>({cnt})</span></div>);})}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:12,alignItems:"center"}}>{[["Source",sO,fSrc,setFSrc],["Sale",saO,fSale,setFSale],["Land",lO,fLand,setFLand]].map(([l,opts,v,sv])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:10,color:"#4a6a4a"}}>{l}:</span><select value={v} onChange={e=>sv(e.target.value)} style={{background:"#131f13",border:"1px solid #2a4a2a",borderRadius:6,color:"#9abaa0",fontSize:11,padding:"4px 7px",cursor:"pointer"}}>{opts.map(o=><option key={o}>{o}</option>)}</select></div>))}<div style={{display:"flex",alignItems:"center",gap:4,marginLeft:"auto"}}><span style={{fontSize:10,color:"#4a6a4a"}}>Sort:</span><select value={sort} onChange={e=>setSort(e.target.value)} style={{background:"#131f13",border:"1px solid #2a4a2a",borderRadius:6,color:"#9abaa0",fontSize:11,padding:"4px 7px",cursor:"pointer"}}><option value="price">Price ↑</option><option value="acres">Acres ↓</option><option value="ppa">$/Acre ↑</option></select></div><span style={{fontSize:10,color:"#4a6a4a"}}>{fil.length} shown</span></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(285px,1fr))",gap:10,marginBottom:24}}>{fil.map(p=><Card key={p.id} p={p} onSelect={setSelected}/>)}</div>
{all.length>0&&<div style={{background:"#0f180f",border:"1px solid #1e3a1e",borderRadius:12,overflow:"hidden"}}><div style={{padding:"11px 16px",borderBottom:"1px solid #1a2e1a",display:"flex",alignItems:"center",gap:7}}><span style={{width:7,height:7,borderRadius:"50%",background:"#5aaa2a",display:"inline-block"}}/><span style={{fontSize:13,fontWeight:700,color:"#90b870"}}>Ask PurelyLand AI</span><span style={{fontSize:11,color:"#3a5a3a"}}>— {all.length} listings loaded</span></div><div style={{maxHeight:200,overflowY:"auto",padding:"12px 16px",display:"flex",flexDirection:"column",gap:8}}>{chat.length===0&&<div style={{color:"#2a4a2a",fontSize:12,fontStyle:"italic"}}>Try: "Best value?" · "Show auctions" · "Owner financing?"</div>}{chat.map((m,i)=>(<div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start"}}><div style={{maxWidth:"82%",background:m.role==="user"?"#1a3a0a":"#131f13",border:`1px solid ${m.role==="user"?"#2a5a0a":"#1e2e1e"}`,borderRadius:m.role==="user"?"12px 12px 2px 12px":"12px 12px 12px 2px",padding:"8px 12px",fontSize:13,color:m.role==="user"?"#b0d880":"#8aaa8a",lineHeight:1.6}}>{m.content}</div></div>))}{chatBusy&&<div style={{color:"#3a5a3a",fontSize:12,fontStyle:"italic"}}>Thinking…</div>}<div ref={chatEndRef}/></div><div style={{padding:"10px 14px",borderTop:"1px solid #1a2e1a",display:"flex",gap:7}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendChat()} placeholder="Ask about listings…" style={{flex:1,padding:"8px 12px",background:"#131f13",border:"1px solid #2a4a2a",borderRadius:7,color:"#b0ccb0",fontSize:13,outline:"none",fontFamily:"inherit"}}/><button onClick={sendChat} disabled={chatBusy||!q.trim()} style={{padding:"8px 14px",background:"#1a4a0a",border:"1px solid #2a6a1a",borderRadius:7,color:"#90c060",fontWeight:700,fontSize:13,cursor:chatBusy?"not-allowed":"pointer"}}>Ask →</button></div></div>}
</>}
</div>
<Modal p={selected} onClose={()=>setSelected(null)}/>
</div>);}

export default function App(){const[page,setPage]=useState("landing");return page==="landing"?<Landing onLaunch={()=>setPage("app")}/>:<SearchApp onBack={()=>setPage("landing")}/>;}
